### PR TITLE
Dark mode

### LINKED ISSUE #10: [GSSOC'21] Toggle Button for Dark and Light mode
Hey, I am Manas Tole a GSSOC'21 Participant.
I want to add a toggle button on each page for Dark and Light mode
This feature is most important to this project as well as  it is convenient to users to use.
Please issue this task to me.
I want to complete this task under your guidance.
Thank-you   :)

@sruti2024

### PR DESCRIPTION
**Pull request by Aditya201551**
# Description:

Added dark mode to the project:
- Added inline dark mode with darkmode.js
- Customized dark mode for each page
- Added `darkmode.js`
- Saving modes according to user
- loading the last saved mode

Fixes #10 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

 
# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

# Screenshots / Video:

https://user-images.githubusercontent.com/32588231/115713737-f9b76d80-a393-11eb-96d3-6d0c324b303d.mp4

@sruti2024 @PROTechThor @chdharm @SaiSudhaV

### CODE REVIEW

**Comment by Aditya201551** [comment]
@dark mode is available for every page

**Comment by sruti2024** [comment]
cool i like the way it works , would be great if u could show how it looks on each page

**Review by sruti2024 — APPROVED** [review]

**Comment by Aditya201551** [comment]
@sruti2024 sure will send you the video link of my google drive

**Comment by Aditya201551** [comment]
@sruti2024 

here is the link to every page's demo [https://drive.google.com/file/d/185aBhECX8aH9BF2VGr5yXPFW5H8FXIuO/view?usp=sharing](ur)

**Comment by mohammedjameel24** [comment]
shout out to the real creator [https://darkmodejs.learn.uno/](url)
open source enthu!

**Comment by Aditya201551** [comment]
> shout out to the real creator [https://darkmodejs.learn.uno/](url)
> open source enthu!

@mohammedjameel24 hey bro chill out, I never said I made this feature all on my own when there is a better way to make thing than why one should create things from scratch and I already said in my pr that I have used darkmode.js so chill and also please review the code lines I have made many custom changes to make this dark mode look good for this specific website I have also written scripts to customize the dark mode for this website, and the code I have used is also opensource, so using that as an option doesn't make me less of an opensource enthu

cheers!

**Comment by Aryamanz29** [comment]
> > shout out to the real creator [https://darkmodejs.learn.uno/](url)
> > open source enthu!
> 
> @mohammedjameel24 hey bro chill out, I never said I made this feature all on my own when there is a better way to make thing than why one should create things from scratch and I already said in my pr that I have used darkmode.js so chill and also please review the code lines I have made many custom changes to make this dark mode look good for this specific website I have also written scripts to customize the dark mode for this website, and the code I have used is also opensource, so using that as an option doesn't make me less of an opensource enthusiast
> 
> cheers!

Could you please squash your commits @Aditya201551

**Comment by sruti2024** [comment]
please fix the conflicting files

**Comment by Aditya201551** [comment]
@sruti2024 i have deleted the conflict file

**Comment by Aditya201551** [comment]
@sruti2024 I have fixed the conflicts

**Comment by Aryamanz29** [comment]
> > > shout out to the real creator [https://darkmodejs.learn.uno/](url)
> > > open source enthu!
> > 
> > 
> > @mohammedjameel24 hey bro chill out, I never said I made this feature all on my own when there is a better way to make thing than why one should create things from scratch and I already said in my pr that I have used darkmode.js so chill and also please review the code lines I have made many custom changes to make this dark mode look good for this specific website I have also written scripts to customize the dark mode for this website, and the code I have used is also opensource, so using that as an option doesn't make me less of an opensource enthusiast
> > cheers!
> 
> Could you please squash your commits @Aditya201551

Reminder : Squash your commits 😅

**Comment by sruti2024** [comment]
@Aditya201551 please make a new PR after cloning this repo once again  , for any further conflict consult with the mentors

**Comment by Aditya201551** [comment]
> @Aditya201551 please make a new PR after cloning this repo once again  , for any further conflict consult with the mentors 

Actually I have solved the conflict so do I have to make a new pr now?

**Comment by Aditya201551** [comment]
> > > > shout out to the real creator [https://darkmodejs.learn.uno/](url)
> > > > open source enthu!
> > > 
> > > 
> > > @mohammedjameel24 hey bro chill out, I never said I made this feature all on my own when there is a better way to make thing than why one should create things from scratch and I already said in my pr that I have used darkmode.js so chill and also please review the code lines I have made many custom changes to make this dark mode look good for this specific website I have also written scripts to customize the dark mode for this website, and the code I have used is also opensource, so using that as an option doesn't make me less of an opensource enthusiast
> > > cheers!
> > 
> > Could you please squash your commits @Aditya201551
> 
> Reminder : Squash your commits 😅 

Admin can do that bro and I am not the admin man😅

**Comment by sruti2024** [comment]
make a new PR

**Comment by Aditya201551** [comment]
okay

**Comment by Aditya201551** [comment]
@Aryamanz29 oh i see, well their was a merge conflict so all the work has been waster as the admin reverted all the changes😥

**Comment by Aryamanz29** [comment]
> @Aryamanz29 oh i see, well their was a merge conflict so all the work has been waster as the admin reverted all the changes😥

No bro , Listen just use earlier `db.sqlite3` file which you have deleted and use `git restore db.sqlite3` and check if everything is working or not if you satisfied with your work then add it to staging area and commit , while pushing if it gives error use `-f` flag on your git push command . I have same conflict on this file and this works for me 😁👍.

**Pull request merged**
