### PR TITLE
PRO_Act Index Page

### PR DESCRIPTION
**Pull request by Sanjana-03**
# Description:
Changes in css of index page

#Issue:
#70 
#21 

Fixes # (issue no.) 

https://user-images.githubusercontent.com/66235278/112357402-80c1e900-8cf5-11eb-9eaf-3cebeaba50cc.mp4

# Screenshots / Video:

### CODE REVIEW

**Comment by Sanjana-03** [comment]
@sruti2024 @chdharm I have resolved conflicts now please check it

**Comment by SaiSudhaV** [comment]
@Sanjana-03 There are some merge conflicts. Please try to resolve them

**Comment by Sanjana-03** [comment]
@SaiSudhaV when you are merging it is showing merging conflicts how can I resolve it???
image

**Comment by sruti2024** [comment]
@Sanjana-03 I don't really like the index page because there is hardly any change , and for the about page I had already told you to change the color , but its not done ! If you are unable to understand what to put up on the index page you can contact with the mentors or me , and as per the merge conflict , there are simultaneous changes therefore this might occur , so unfork the  repo and fork it once again and install the requirements.

**Comment by sruti2024** [comment]
@Sanjana-03 also please clarify on which issue is this PR made??

**Pull request closed without merging**
