### PR TITLE
Updated the README

### LINKED ISSUE #42: Add important steps in the README.md file
Hello..
I would like to add some important steps in the 'Getting Started' section of the readme file like installing the virtual environment before cloning the project and install the requirements.txt file . It would be very helpful for beginners who want to get started.

PS: I am a GSSOC21 participant and would want to work in this project.
Thank You.

### PR DESCRIPTION
**Pull request by 2001asjad**
Added the steps to create and activate the virtual environment and also install the project dependencies .
Fixes #42.

### CODE REVIEW

**Comment by PROTechThor** [comment]
@2001asjad Hey. I don't think we should have only Windows-specific instructions. We either have instructions for Linux as well or not at all. Do the virtual environment commands work on Linux as well?

**Comment by 2001asjad** [comment]
@PROTechThor I have addressed the changes. Please take a look

**Comment by PROTechThor** [comment]
Hi @2001asjad. Can you please fix the conflicts here?

**Review by PROTechThor — APPROVED** [review]
Looks good, aside from the conflicts.

Another mentor is free to merge this once the conflicts are fixed

**Pull request merged**
