### PR TITLE
Adding a Simple Pre-loader

### PR DESCRIPTION
**Pull request by sahilempire**

### CODE REVIEW

**Comment by sruti2024** [comment]
please attach a video of the whole functioning of this loader !

**Review by PROTechThor — CHANGES_REQUESTED** [review]
@sahilempire Please attach a video of the loader in action

**Comment by sahilempire** [comment]
@sruti2024 , this is the **video of required Pre-loader**
`https://drive.google.com/file/d/169Buhwlf3nt6dHDEX5t7oAN5845-3NMo/view?usp=drivesdk` .

If you think this is good, then **please merge my first pull request.**
Thank you

**Review by sahilempire — COMMENTED** [review]
Reviewed as per @PROTechThor

**Comment by sahilempire** [comment]
https://user-images.githubusercontent.com/66163158/111882241-9c1db300-89da-11eb-9b74-dbc2aedbffa8.mp4

**Comment by PROTechThor** [comment]
Hi @sahilempire. The loader looks nice! Why doesn't the video doesn't show the transition from the loader to the actual site content?

**Comment by sahilempire** [comment]
Okay, let me input new video which show actual site after loading @PROTechThor

**Comment by SaiSudhaV** [comment]
@sahilempire Please try to resolve the merge conflicts

**Comment by sahilempire** [comment]
@sruti2024 I have **tried serval times**, but these are not resolving,
**Please guide** me through so that **I can resolve these conflicts**.

Thank you.

**Comment by SaiSudhaV** [comment]
@sahilempire try to unfork and fork the repo again. Also, clone the repo again.

**Comment by sahilempire** [comment]
@SaiSudhaV **conflicts resolved**!

Thank you mam.

**Pull request closed without merging**
