### PR TITLE
[Fix] : Social auths and Added Github OAuth

### LINKED ISSUE #193: Feature : Reimplement Social login
### **Feature request**:
-  We have already social logins like `Google, Facebook` but it contains a lot of bugs and not properly implemented in this project.
-  Feel free to research more about how to implement `social auth, login system` for the Django project.
-  This feature should be` secure, efficient, and robust`.
-  Also remove the current social login feature because it contains so many bugs (Mostly are seen after if we made changes to the `database`) also less secure ( since it exposing `API keys` in project settings)
-  First, discuss your approach with project `admins/mentors` before start working on this issue.
- Mark this issue `LEVEL3` 

<hr/>

Screenshot (124)
**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

### PR DESCRIPTION
**Pull request by Aryamanz29**
# Description:
-  Solved existing auth problem
-  Added keys to `.env`
-  Added `Github OAuth` to App
-  `Note:` If you have the same **e-mail registered** with **GitHub** and **Google** it might give you an error because, Acc to `django-alluth`  we can't create a user with the same email for 2 socials accounts, So you have to choose only **one option** to sign up to avoid this error.

Fixes #193

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

 
# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

# Screenshots / Video:
Screenshot from 2021-05-29 14-50-51
Screenshot from 2021-05-29 14-50-56

### CODE REVIEW

**Comment by SaiSudhaV** [comment]
@Aryamanz29 Please do attach a working demo video with all the following:
case1 : When a user is not registered
case2 : When the user is logged in with google or github blocking the entry from the other social account.

**Comment by Aryamanz29** [comment]
> @Aryamanz29 Please do attach a working demo video with all the following:
> case1 : When a user is not registered
> case2 : When the user is logged in with google or github blocking the entry from the other social account.

**CASE - 1**  When user not registered 👇 

auth1

**CASE - 2**  When user first login with Github then after with Google with the same email registered on both socials, he/she might get this form/error, So it is preferred to use only a single auth service  either google or GitHub  if you have the same email registered with both social auth in my case ie. aryamanz29@gmail.com 👇 

auth2

auth3

**Comment by SaiSudhaV** [comment]
> > @Aryamanz29 Please do attach a working demo video with all the following:
> > case1 : When a user is not registered
> > case2 : When the user is logged in with google or github blocking the entry from the other social account.
> 
> **CASE - 1** When user not registered 👇
> 
> auth1
> 
> **CASE - 2** When user first login with Github then after with Google with the same email registered on both socials, he/she might get this form/error, So it is preferred to use only a single auth service either google or GitHub if you have the same email registered with both social auth in my case ie. [aryamanz29@gmail.com](mailto:aryamanz29@gmail.com) 👇
> 
> auth2
> 
> auth3

In case2 the redirection of login to google accounts was it default one or was it created in our project?

**Comment by Aryamanz29** [comment]
> > **CASE - 1** When user not registered point_down
> > auth1
> > **CASE - 2** When user first login with Github then after with Google with the same email registered on both socials, he/she might get this form/error, So it is preferred to use only a single auth service either google or GitHub if you have the same email registered with both social auth in my case ie. [aryamanz29@gmail.com](mailto:aryamanz29@gmail.com) point_down
> > auth2
> > auth3
> 
> In case2 the redirection of login to google accounts, was it default one or was it created in our project?

In case2 first gif , I show you that both GitHub and Google auth sevice won't work if user have same registered email , but in second gif of case2 or gif of case1 you see that  he/she can use  either GitHub or google but not both.

**Pull request merged**
