### PR TITLE
Change Password functionality added

### PR DESCRIPTION
**Pull request by somya51p**
# Description:

Users once logged in, don't have the option to change their password. So added the change password option.
This is an additional functionality as users like changing their passwords after a certain time due to security issues.

Fixes # (issue no.) 
This is pull request for issue number #82.

## Type of change:

- [x] New feature (non-breaking change which adds functionality)
 
# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

# Screenshots / Video:
Change password page

Alert message displaying if password changed and also for error if any.

Added Change password button in profile page

@sruti2024 @SaiSudhaV Please review the same, and suggest changes if any.

### CODE REVIEW

**Comment by SaiSudhaV** [comment]
@somya51p The appearance of the pages is very nice. Please even try to attach the demo. I feel it would be better if you add the background color instead of leaving it plain.

**Comment by somya51p** [comment]
In 1st case, putting the incorrect password in confirm password section.
In the 2nd case, converting old password to new password successfully.
In the 3rd case, putting the wrong old password, so the page is redirecting to the login page.


https://user-images.githubusercontent.com/64978837/112670891-bc0c0700-8e1e-11eb-9bf7-3370b50cfaf0.mp4




@SaiSudhaV Please review the demonstration video. And the orientation of the profile page is disturbed so can I raise a new issue for the same and enhance the styling of the profile page? Please suggest the needful.

**Comment by SaiSudhaV** [comment]
@somya51p Gone through demo video it is very nice, try to resolve the merge conflicts

**Comment by somya51p** [comment]
@SaiSudhaV I have resolved the merge conflicts. Please review the same. ThankYou!

**Comment by SaiSudhaV** [comment]
@somya51p Great work !! you can start with the orientation of the profile page by creating an issue. Please ensure if there is an existing issue before you create. Thanks for contributing!

**Pull request merged**
