### PR TITLE
Nav-Bar Styling

### LINKED ISSUE #21: Improve the Navbar design
Currently we have a very basic navbar so improve the design of the navbar  keeping the content same .

### PR DESCRIPTION
**Pull request by SalmaFarghaly**
# Description:
Restyling the Nav Bar according to the styling that was mentioned in issue

Fixes #21 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

 
# Checklist:

- [ x] My code follows the style guidelines of this project.
- [ x] I have performed a self-review of my own code.
- [x ] I have commented my code, particularly in hard-to-understand areas.
- [ x] My changes generate no new warnings.
.

# Screenshots / Video:

https://user-images.githubusercontent.com/59613960/115966335-6b76ef00-a52d-11eb-9371-d368ec538c93.mp4

### CODE REVIEW

**Comment by sruti2024** [comment]
good work , as expected , just remove that something else  from the drop down of projects tab

**Comment by SalmaFarghaly** [comment]
@sruti2024 Thank you.
Done I have removed "something else"

**Comment by sruti2024** [comment]
there seems to be some conflicts please resolve them

**Comment by SalmaFarghaly** [comment]
@sruti2024 I think the conflicts are resolved now

**Comment by SalmaFarghaly** [comment]
I think that was because of the last merging pull request, I have solved it now please check it and let me know if it is not solved yet

**Comment by sruti2024** [comment]
yup done !!

**Pull request merged**
