### PR TITLE
[Feature] added Google Authentication

### PR DESCRIPTION
**Pull request by Aditya201551**
Added the feature with regard to issue #58 (**Google login**)

-> Added a `Sign in with Google` button 
-> Updated requirements.txt file for the new features
-> Setup settings.py for authentication purpose
-> Updated views and URL files

The above updates are working completely fine and are deployable to the main branch

Screenshot (41)

@sruti2024

### CODE REVIEW

**Comment by sruti2024** [comment]
it would be very nice if you could attach a video depicting the whole working !

**Comment by Aditya201551** [comment]
@sruti2024 video link, please review: [https://drive.google.com/file/d/1Ce0ng-MbBiBDzef1_n6JyDP5iBemWmQH/view?usp=sharing](Drive Link)

**Comment by Aditya201551** [comment]
@sruti2024 Video link, please review: [https://drive.google.com/file/d/1Ce0ng-MbBiBDzef1_n6JyDP5iBemWmQH/view?usp=sharing](url)

**Comment by Aditya201551** [comment]
@sruti2024 

[ https://drive.google.com/file/d/1Ce0ng-MbBiBDzef1_n6JyDP5iBemWmQH/view?usp=sharing](url)

**Pull request merged**
