### PR TITLE
Enhanced the UI of view Projects

### LINKED ISSUE #180: UI of view Projects
I would like to give it a try to make ui of view projects  better.

**Note : The image is not saving in db so i can't render it on view project page . it will show image not found or i can hard code the image part** 

I can make a better ui for The data currently on that page using bootstrap cards 
It will look something like this.
ui of cards

### PR DESCRIPTION
**Pull request by arpit456jain**
# Description:

Enhanced the UI of view Projects

Fixes #180 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

 
# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

# Screenshots / Video:

https://user-images.githubusercontent.com/55352601/117124301-c920fc00-adb5-11eb-9def-ff52ba8eec19.mp4

### CODE REVIEW

**Comment by arpit456jain** [comment]
@sruti2024 kindly review my PR 
previously i was thinking to add only a card but when you asked to add something more that's why i added the table and some Cool CSS to it , I hope it will get a good label

**Comment by sruti2024** [comment]
seems good but instead of having the two tables as top down have it side by side , and it had a feature of on click complete hope that is not hampered , else the  things are pretty cool . and also make sure that it is responsive

**Comment by arpit456jain** [comment]
> seems good but instead of having the two tables as top down have it side by side , and it had a feature of on click complete hope that is not hampered , else the things are pretty cool . and also make sure that it is responsive

@sruti2024 don't worry that feature of on click complete is working fine i had checked it and for responsiveness i had placed it up side down other wise in mobile view it will create problem 

I tried to put both table side my side but it was not working.
I will try again

**Comment by arpit456jain** [comment]
Making a new PR unable to resolve conflicts

**Comment by arpit456jain** [comment]
#189

**Pull request closed without merging**
