### PR TITLE
#10 Toggle Button for Dark and Light mode

### PR DESCRIPTION
**Pull request by sahilempire**
# Description:

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue no.) 
#10 

## Type of change:
Toggle Button for Dark/Bright Mode Added.

# Checklist:

- [x] New feature (non-breaking change which adds functionality)
- [x] New and existing unit tests pass locally with my changes.

# Screenshots / Video:

https://user-images.githubusercontent.com/66163158/115124594-a6829b00-9fe0-11eb-9249-b8c7399ee1b8.mp4

### CODE REVIEW

**Review by sahilempire — COMMENTED** [review]
Reviewed!

**Review by sahilempire — COMMENTED** [review]
Done.

**Comment by sruti2024** [comment]
is this added on each page?? if not please do it and don't have the writing in white its not visible

**Review by SaiSudhaV — APPROVED** [review]

**Comment by arpit456jain** [comment]
@sahilempire did you check to refresh the page after activating the dark mode . I don't think so your code can handle it .

Just try this one .  activate dark mode and then refresh the page , if it is still in  dark mode than its good other wise the feature is not working properly

**Comment by Aryamanz29** [comment]
@sahilempire Never raise PR through base branch ie. `main` you should checkout different one. What do you think @sruti2024 ?. Have you read [contributing guidelines](https://github.com/sruti2024/PRO_Act/blob/main/contributing.md) before raising this PR? @sahilempire .
- Add proper commits messages and squash them once your feature is ready.

**Comment by sahilempire** [comment]
@Aryamanz29 okay sir, I will keep this important guideline in my mind.

Thank you.

**Comment by Aryamanz29** [comment]
> @Aryamanz29 okay sir, I will keep this important guideline in my mind.
> 
> Thank you.

Don't call me sir please 😜 btw PR looks  good 💯.

**Review by PROTechThor — APPROVED** [review]
Looks good, but for the merge conflict

**Pull request closed without merging**
