### PR TITLE
Modified the variable names

### LINKED ISSUE #170: Rename : Variable/Function names
**A good variable name should:**
```
Be clear and concise.
Be written in English. ...
Not contain special characters. ...
Not conflict with any Python keywords, such as for, True, False, and, if, or else .
```
- Different or Bad variables creates problem in debugging and it should be avoided.
-  Rename `variable, functions, etc` name in project `source code`
-  They should `follow` a similar variable naming convention throughout the project. ref  https://www.theserverside.com/definition/Snake-case

### SS below 👇:
- **Existing code** 

Screenshot (100)_LI

Screenshot (101)_LI

Screenshot (102)_LI

### PR DESCRIPTION
**Pull request by Furquan712**
# Description:

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #170 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

 
# Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

# Screenshots / Video:

### CODE REVIEW

**Comment by SaiSudhaV** [comment]
@Furquan712 Have you verified whether all the files have proper naming for variables and functions or not?

**Comment by Furquan712** [comment]
i have check all the variable. you can recheck if u want....

**Comment by Aryamanz29** [comment]
Hii 👋 @Furquan712 

-  Have you tested this commit before raising this PR, since it breaks the login feature of this project?
-  Have you check that you've replaced all occurrences of variables/function names in other files as well?
-  Some function names in `views.py` & `models.py` still uses camel notation like `loginUser() ,signupUser()` etc please change them as well.

@SaiSudhaV  Please revert this PR for now and review it again after the completion of the requested changes ✔

**See this 👇**
Note: I have also check this with the last commit ie. 008ceb7 and it works as expected (Found no problem).

login_bug

**Comment by SaiSudhaV** [comment]
@Aryamanz29 Thank you so much. Sure I'll review it again.

**Pull request merged**
