### PR TITLE
Pro_act compact logo

### PR DESCRIPTION
**Pull request by Tannusharma28**
proact compact logo ai_17-03-2021-page-001

### CODE REVIEW

**Review by PROTechThor — CHANGES_REQUESTED** [review]
Hi @Tannusharma28 

Thanks for working on this. I like the idea behind the logo. The checkmark idea is pretty cool :D

I think a few changes can be made:
- Can you remove the gradient? I don't think it's necessary
- Make the outer line thicker, so that it can be visible in small sizes
- Can you try other colors? This shade of green is not too good to me. 
- Don't put the text inside the logo icon. Either place it at the side or bottom. 

Thanks. I'm waiting for your improvements :)

**Comment by Tannusharma28** [comment]
> Hi @Tannusharma28
> 
> Thanks for working on this. I like the idea behind the logo. The checkmark idea is pretty cool :D
> 
> I think a few changes can be made:
> 
> * Can you remove the gradient? I don't think it's necessary
> * Make the outer line thicker, so that it can be visible in small sizes
> * Can you try other colors? This shade of green is not too good to me.
> * Don't put the text inside the logo icon. Either place it at the side or bottom.
> 
> Thanks. I'm waiting for your improvements :)

I have updated Logo design.
You can check it!

**Comment by garvitraj** [comment]
@sruti2024 can i work on this issue to provide a better logo design.
I m a graphic designer so i think my skills will surely be helping me to get a better logo for us

**Comment by PROTechThor** [comment]
Hi @garvitraj. You can submit your own PR with your design if you want :)

**Review by PROTechThor — CHANGES_REQUESTED** [review]
Hello @Tannusharma28 

This looks so much better. A few more changes and this will be good to go: 

1. The text at the bottom is too small. Please reduce the icon size to match the text. Look at these for inspiration:
    - https://as1.ftcdn.net/jpg/00/97/53/86/500_F_97538607_csuSdSWdHqndsDo1gtlr4w98fBedG05i.jpg
    - https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDecDtQLXDZpx_N-4CbkQNT9fxtdaEjdb7RQ&usqp=CAU
 2. I don't think we need the hyphen in the name. Instead of "PRO_Act", let's use "PRO Act". Also, try bolding the second word and see how it looks? 
 3. Please submit an SVG file, so that we can make minor changes to the logo if necessary. 

Thank you for working on this :)

**Comment by garvitraj** [comment]
@PROTechThor ok will submit it by today

**Comment by Tannusharma28** [comment]
> Hello @Tannusharma28
> 
> This looks so much better. A few more changes and this will be good to go:
> 
> 1. The text at the bottom is too small. Please reduce the icon size to match the text. Look at these for inspiration:
>    
>    * https://as1.ftcdn.net/jpg/00/97/53/86/500_F_97538607_csuSdSWdHqndsDo1gtlr4w98fBedG05i.jpg
>    * https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDecDtQLXDZpx_N-4CbkQNT9fxtdaEjdb7RQ&usqp=CAU
> 2. I don't think we need the hyphen in the name. Instead of "PRO_Act", let's use "PRO Act". Also, try bolding the second word and see how it looks?
> 3. Please submit an SVG file, so that we can make minor changes to the logo if necessary.
> 
> Thank you for working on this :)


WhatsApp Image 2021-03-20 at 2 23 58 PM

This doesn't support SVG or ai files. 
So, submitting a pdf file.
[ProAct logo.pdf](https://github.com/sruti2024/PRO_Act/files/6175164/ProAct.logo.pdf)

**Comment by PROTechThor** [comment]
> This doesn't support SVG or ai files.

@Tannusharma28 
I mean that you should upload the SVG file to the repo, not add it as a comment

**Comment by garvitraj** [comment]
@PROTechThor i m attaching the logo file here and will be making the PR if finalize will give illustrator file
Pro_Act-LOGO1

**Comment by PROTechThor** [comment]
@garvitraj Please make a separate PR with your won logo submission. I can't review your design on someone else's PR. That won't be right.

**Comment by PROTechThor** [comment]
Hi @Tannusharma28. 
Can you please create a new folder called "logo" under /static/images? Then place your logo into the folder. Also, upload an editable SVG file of the logo. Thanks for coming this far :)

**Comment by PROTechThor** [comment]
Thanks!

**Pull request merged**
