### PR TITLE
PRO_ACT Index page 

### PR DESCRIPTION
**Pull request by Sanjana-03**
# Description:
Changes in css of index page
 #Issue:
#70 
#21 

# Screenshots / Video:
image

### CODE REVIEW

**Comment by sruti2024** [comment]
there need to be a lot of improvement :
1. link the issue to this pr
2. the accordion seems to lead no where but plain bootstrap text , so cant really understand the purpose .
3. there are merge conflicts try resolving them.

**Comment by Sanjana-03** [comment]
Actually in accordion Explanation of steps should come then it will be of use??

**Comment by SaiSudhaV** [comment]
@Sanjana-03 please attach the demo video instead of the screenshot so that it'd be helpful to review. And try to make the other changes also which are suggested by @sruti2024

**Comment by Sanjana-03** [comment]
Sure, I will do that.

**Comment by Sanjana-03** [comment]
@sruti2024 

Please see the demo


https://user-images.githubusercontent.com/66235278/112015339-bd54df80-8b51-11eb-9b8e-03c26b428dfd.mp4

**Comment by PROTechThor** [comment]
@Sanjana-03 Just pointing out that there are some merge conflicts here, in case you missed it :)

**Pull request closed without merging**
