### PR TITLE
added footer in base.html file

### LINKED ISSUE #1: Add Footer in the base file
Add a footer with the copyright, contact details  and social media handles . Add this to the base.html file in templates . Needs to be responsive !

### PR DESCRIPTION
**Pull request by sujoy-coder**
This PR fixes #1 and #54

@sruti2024 Let me know if any modification required

### CODE REVIEW

**Comment by PROTechThor** [comment]
@sujoy-coder Hi. Can you please upload a screenshot of the footer here? It'll make this easier to review. Thanks!

**Comment by sujoy-coder** [comment]
### Screenshot of footer in webpage
please check it @PROTechThor @sruti2024 

Screenshot (74)

**Comment by sujoy-coder** [comment]
This PR also fixes #54 
which was opened by myself
Please Check it

**Comment by PROTechThor** [comment]
@sujoy-coder Looks great! Thank you :)

I'll leave merging to @sruti2024 , if it looks good to her as well.

**Review by PROTechThor — APPROVED** [review]

**Comment by sruti2024** [comment]
Seems perfect to me as well !!

**Pull request merged**
