### PR TITLE
Enhanced CSS of project_add page

### LINKED ISSUE #2: Enhancement of CSS of project add page
Improvise the UI UX of the project add page , try using external css/JS only to keep the code clean .

### PR DESCRIPTION
**Pull request by vismitap**
Fixed #2

# Description:

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Changes made:

- Added box-shadow to navbar
- Fixed the margin issues in navbar and all form elements and now they do not appear to stick to each other.
- Added a card and put the form inside card
- Added box-shadow to card as well
- Changed the title and button color also.
- Applied prettier to format the documents to make it more readable 

Fixes #2 

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

 
# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

# Screenshots / Video:

 Old SS :  
 image 

New SS:
image
image

### CODE REVIEW

**Comment by SaiSudhaV** [comment]
@vismitap Can you please add the working demo video along with screenshots and resolve the merge conflicts

**Comment by vismitap** [comment]
> @vismitap Can you please add the working demo video along with screenshots and resolve the merge conflicts

Yes sure! I was about to put a video but there was some problem with the game bar and could no record. I will try to resolve this asap!

**Comment by vismitap** [comment]
The video for this issue: https://i.imgur.com/hTX6TTl.mp4

**Comment by vismitap** [comment]
@SaiSudhaV, @PROTechThor  I had one question, when `db.sqlite3` is already in .gitignore file why is it getting committed? I had already solved all the conflicts and was waiting for this to be reviewed. Because the `db.sqlite3` is getting committed by everyone, the binary file changes and again raises conflicts! Please look into this!

**Comment by SaiSudhaV** [comment]
@vismitap Tryto unfork the repo and fork it once again and install the requirements. clone the repo again and check if the conflicts are resolved.

**Comment by vismitap** [comment]
> @vismitap Try to unfork the repo and fork it once again and install the requirements. clone the repo again and check if the conflicts are resolved.

Yes I will try that. But the question was: A file that is included in `.gitignore` file should get committed right? I didn't understand this. Please guide me with this!

**Comment by SaiSudhaV** [comment]
Yes .gitignore should not be committed. Whenever you commit all changes together, all the changed files, including binary files, will get committed. But you should not push binary files into git, as the git considers a binary file as a normal file it stores all the changed versions, which might create conflicts. If the binary files are small then it doesn't affect much you can push but when the files are large it is not required. So to avoid these conflicts better not to push them.

**Comment by sruti2024** [comment]
@PROTechThor please see to this conflict issue

**Comment by sruti2024** [comment]
@vismitap do a thing clone the repo one again make the changes and create a PR there were changes , as some more field were added , please do them

**Comment by vismitap** [comment]
> @vismitap do a thing clone the repo one again make the changes and create a PR there were changes , as some more field were added , please do them

Yes sure! Will do that and raise a new PR!

**Comment by Aryamanz29** [comment]
> > @vismitap do a thing clone the repo one again make the changes and create a PR there were changes , as some more field were added , please do them
> 
> Yes sure! Will do that and raise a new PR!

@vismitap  Any updates?

**Comment by vismitap** [comment]
> > > @vismitap do a thing clone the repo one again make the changes and create a PR there were changes , as some more field were added , please do them
> > 
> > 
> > Yes sure! Will do that and raise a new PR!
> 
> @vismitap Any updates?

Will do that tomorrow...was Busy with college work so could not do

**Comment by Aryamanz29** [comment]
@vismitap Also squash your commits for clean commit history.

**Comment by Aryamanz29** [comment]
> @vismitap Once your resolve conflicts make sure to squash your commits for clean commit history.

**Comment by Aryamanz29** [comment]
@vismitap Once your resolve conflicts make sure to squash your commits for clean commit history.

**Pull request closed without merging**
