### PR TITLE
[fix]: Multiple project with same name

### LINKED ISSUE #158: Bug : Adding multiple project with same name
### **Describe the bug:**
Adding multiple projects with the same name causes `MultipleObjectsReturned` error 

#### **See this 👇**

Screenshot (79)

same_project

### **Expected behavior:**
- Add project form must have constraints for adding new projects ie. it should alert that  **_"Project with same name already exists!!!"_**

<hr/>

### PR DESCRIPTION
**Pull request by Aryamanz29**
# Description:

- Fix: Multiple projects with the same name
- Now the user sees the warning before adding a project that already exists.

Fixes #158

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

 
# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

# Screenshots / Video:
add_project

### CODE REVIEW

**Comment by SaiSudhaV** [comment]
@Aryamanz29 I think it would be better if the warning is shown while entering the project name itself before clicking on submit (like if we change our username in Instagram or some other websites will display an error message showing that the username is available). Can that be done? What do you think about this idea? @sruti2024

**Comment by Aryamanz29** [comment]
> @Aryamanz29 I think it would be better if the warning is shown while entering the project name itself before clicking on submit (like if we create a google groups, mail ids, Instagram or some other websites will display an error message showing that the username is available). Can that be done? What do you think about this idea? @sruti2024

Sure, I think for this, I need to add constraint in the form itself. I'll try to do this 👍

**Comment by SaiSudhaV** [comment]
Okay, once you're done with that we'll go for merging

**Comment by Aryamanz29** [comment]
> @Aryamanz29 I think it would be better if the warning is shown while entering the project name itself before clicking on submit (like if we create a google groups, mail ids, Instagram, or some other websites will display an error message showing that the username is available). Can that be done? What do you think about this idea? @sruti2024

**Updates⚡**
- Added project name suggestion whenever user types on `input field` of `project name` using `AJAX`  & added `static/js/project_name_validation.js `
  - Suggestions includes like project already exists, available etc
- I haven't remove existing  `Django alert messages` because if someone tries to submit the form with an `empty project name` it gives back an alert and 

`redirects` the same page and I think which is necessary.
- **See working 👇**

multiple_pro_final-min

**Comment by Aryamanz29** [comment]
@SaiSudhaV  Please review PR again

**Comment by SaiSudhaV** [comment]
Woah! Nice looking great. No problem let that default Django alert message.
Thanks for your contributions. Keep working.

**Review by SaiSudhaV — APPROVED** [review]

**Pull request merged**
