### PR TITLE
  PRO_ACT LOGO

### PR DESCRIPTION
**Pull request by preetiahuja18**
**PRO_ACT LOGO**
logo

### CODE REVIEW

**Review by PROTechThor — CHANGES_REQUESTED** [review]
Hi @preetiahuja18 

Thanks for doing this. For now, I don't really like the general idea behind the logo. Why are you using a telescope icon? Also, the icon is way too small compared to the text. 

Please, submit a better logo design. This one is not unique enough. Have you tried looking at the logos of similar projects for inspiration?

**Comment by preetiahuja18** [comment]
I have changed the logo. Please check it once. .if anything  u want to change , please tell me.

**Comment by preetiahuja18** [comment]
Check one this also.. @PROTechThor 
proact logo

**Review by PROTechThor — CHANGES_REQUESTED** [review]
Hi @preetiahuja18 

I do like the logo design. It looks really professional and cool. Can you please explain how this logo design fits into PRO_Act's functionality? What does the logo represent? 

Thanks!

**Comment by preetiahuja18** [comment]
Hi, @PROTechThor 
In 1st logo ,task book is shown and  it also shows our task list, and manage our task what we have to do.
In 2nd logo, From my opinion, if we complete goals of our life by task to task with dividing them in a list  ,then surely we will achieve success. [ logo represent- a student standing ,who has achieved his goal. and as we all know, A goal without a plan is just a wish!
Thank you!

**Comment by SaiSudhaV** [comment]
Hi @preetiahuja18
The idea behind the logo is nice.
Can you please change the font style in the 2nd logo.

**Comment by preetiahuja18** [comment]
Thank You for feedback @SaiSudhaV  :) 
Yeah sure,I will change the font style in logo 2. Which style u want ..please tell me.

**Comment by SaiSudhaV** [comment]
@preetiahuja18 Check the styles in the following link and pick any of the styles that you feel best suits the logo
https://www.designcuts.com/learning-hub/articles/30-fonts-for-logo-design-every-designer-should-own/

**Comment by preetiahuja18** [comment]
Done @SaiSudhaV !
Untitled

**Comment by preetiahuja18** [comment]
@SaiSudhaV @PROTechThor 
Any updates for this logo?

**Comment by SaiSudhaV** [comment]
Hi, @preetiahuja18 the logo is looking great. No changes are required

**Comment by preetiahuja18** [comment]
Okay, So what's next step for me? @SaiSudhaV

**Comment by PROTechThor** [comment]
Hi @preetiahuja18 
Can you please create a new folder called "logo" under /static/images? Then place your logo into the folder. Also upload an editable SVG file of the logo. Thanks for coming this far :)

**Comment by preetiahuja18** [comment]
Done! @PROTechThor  please check it once.

**Comment by PROTechThor** [comment]
@preetiahuja18 You haven't added the SVG file to the folder yet

**Comment by sruti2024** [comment]
@preetiahuja18 any update or should this be closed?

**Comment by preetiahuja18** [comment]
@sruti2024 Sorry I was  busy in practicals and exams. I have  created a new folder and uploaded  a  SVG file of the logo.  Please check it once.

**Comment by Aryamanz29** [comment]
> @sruti2024 Sorry I was busy in practicals and exams. I have created a new folder and uploaded a SVG file of the logo. Please check it once.

Any updates? @preetiahuja18

**Comment by preetiahuja18** [comment]
I have uploaded the logo from my side. @Aryamanz29

**Pull request closed without merging**
