### PR TITLE
nandini7637 made responsive about page

### PR DESCRIPTION
**Pull request by nandini7637**
#8 
@sruti2024 I have made a PR for about page please check it and if any modifications are to be done please tell.
thanks!

### CODE REVIEW

**Comment by sruti2024** [comment]
@nandini7637  Could you attach any screen shorts or video for me to see the changes

**Comment by nandini7637** [comment]
@sruti2024  yeah sure, can I email you a reference video?

**Comment by nandini7637** [comment]
@sruti2024 please check ur email

**Comment by nandini7637** [comment]
@sruti2024 please check discord dm
Thanks!

**Pull request merged**
