### PR TITLE
Done !!! User Profile Displaying Route

### LINKED ISSUE #15: Create a route for displaying User Profile
Hi @sruti2024 , I would like to work on this issue as a participant of GSSoC'21. Here I am thinking to create css card view for the user profile which contains Information of the user.

please assign it to me 🙏

### PR DESCRIPTION
**Pull request by sujoy-coder**
Hey @sruti2024 , I have implemented  profile page for user. Please check it and let me know  any changes need to be done or not. I have attached the demo video for your reference.
fixes #15 

Thank You … 🙏

https://user-images.githubusercontent.com/65298629/110782487-33716080-828d-11eb-8b43-fce49c5c8891.mp4

### CODE REVIEW

**Comment by sruti2024** [comment]
Great job !! could u please widen the profile card because the page seems a bit empty, and also follow this color scheme https://colorhunt.co/palette/269111

**Comment by sujoy-coder** [comment]
Hi @sruti2024 , I have changed the card view. Now please check it.

View of Card Profile :
Screenshot (16)

**Comment by sruti2024** [comment]
great work!

**Comment by sujoy-coder** [comment]
Thank you @sruti2024 🤘

**Comment by Aditya201551** [comment]
Hello, @sujoy-coder great work! but I just wanted to say that after forking the project and running it locally, it's throwing an error:
ScreenShot attached below!

Screenshot (42)


please fix this issue

**Comment by sujoy-coder** [comment]
#### Please run the following command 
`python manage.py migrate run-syncdb`

**Pull request merged**
