### PR TITLE
[Gssoc'21] Enhancing the footer 

### LINKED ISSUE #101: [Gssoc'21] Enhancing the footer
### **Feature request**:
I want to improve the current footer, as it is currently very dull and simple.

### PR DESCRIPTION
**Pull request by arpit456jain**
# Description:

https://user-images.githubusercontent.com/55352601/113819985-be178380-9797-11eb-93f8-f100abfeb75f.mp4

Fixes #101 

## Type of change:

- [x] New feature (non-breaking change which adds functionality)
 
# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by arpit456jain** [comment]
@sruti2024 kindly review my PR

**Review by PROTechThor — APPROVED** [review]
Looks cool to me. Thanks!

I'll let another mentor merge if they approve

**Comment by sruti2024** [comment]
please could u reduce the height of the wave

**Comment by arpit456jain** [comment]
> please could u reduce the height of the wave

Yeah sure kindly review my PR

> please could u reduce the height of the wave

Yeah sure..
Kindly review my PR #111 as its a very small issue and i am working on 2 different branches it may cause conflicts.

**Comment by arpit456jain** [comment]
@sruti2024 please review this

**Comment by arpit456jain** [comment]
@sruti2024

**Pull request merged**
