### PR TITLE
Enhanced CSS of add project page

### PR DESCRIPTION
**Pull request by somya51p**
# Description:
Enhanced CSS of add project page

Fixes # (issue no.) 
Issue number #2 

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)
 
# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.

# Screenshots / Video:

@sruti2024 @SaiSudhaV Please review the PR. And suggest changes if any.

### CODE REVIEW

**Review by SaiSudhaV — APPROVED** [review]

**Comment by sruti2024** [comment]
could u please remove this gradient instead have the shadow effect and keep the box white and make the background colored , bring the image upload label beside technical stack, and submit button at the center

**Comment by Aryamanz29** [comment]
@somya51p  I think adding inline CSS or internal CSS for bigger projects is not good practice because it becomes less digestible to new contributors. I think it could be better if you create a separate CSS file in ` ./static/`  and link it to `project_add.html`. What do you think @sruti2024?

**Comment by somya51p** [comment]
> @somya51p I think adding inline CSS or internal CSS for bigger projects is not good practice because it becomes less digestible to new contributors. I think it could be better if you create a separate CSS file in ` ./static/` and link it to `project_add.html`. What do you think @sruti2024?

@Aryamanz29 Yes you are right. I think then we need to create a separate issue for the same, because all pages have either internal or inline css. What say shall I work on that? @sruti2024

**Comment by Aryamanz29** [comment]
> > @somya51p I think adding inline CSS or internal CSS for bigger projects is not good practice because it becomes less digestible to new contributors. I think it could be better if you create a separate CSS file in ` ./static/` and link it to `project_add.html`. What do you think @sruti2024?
> 
> @Aryamanz29 Yes you are right. I think then we need to create a separate issue for the same because all pages have either internal or inline CSS. What say shall I work on that? @sruti2024

Sure I'll create an issue for that 👍

**Comment by sruti2024** [comment]
@somya51p are the changes done??

**Comment by somya51p** [comment]
> @somya51p are the changes done??

@sruti2024 Will do it till tomorrow.

**Comment by sruti2024** [comment]
@somya51p updates?

**Comment by somya51p** [comment]
> @somya51p updates?

@sruti2024 In making background coloured shadow effect is not coming that much effectively. What are your views on that?

**Comment by sruti2024** [comment]
okay then just try with a border

**Comment by SaiSudhaV** [comment]
@somya51p Any updates?
Once you are done making changes, ensure resolving merge conflicts

**Pull request closed without merging**
