### PR TITLE
Logo for Pro Act

### PR DESCRIPTION
**Pull request by garvitraj**
Kindly review and any suggestions then pls inform for improvement.
i tried to use the colour as given in readme section

### CODE REVIEW

**Comment by sruti2024** [comment]
seems good just change the font of pro act  and it will be written as PRO_Act

**Comment by garvitraj** [comment]
will surely do it by today

**Comment by garvitraj** [comment]
@sruti2024 added an new logo file just as per ur guide line pls review it

**Comment by PROTechThor** [comment]
@garvitraj I like the general idea behind the logo. Please upload the editable SVG file as well, so we can make changes if required. Thanks!

**Comment by garvitraj** [comment]
@PROTechThor sure will do it

**Review by PROTechThor — CHANGES_REQUESTED** [review]
Should be good to merge once the SVG is uploaded.

**Comment by garvitraj** [comment]
@PROTechThor should i upload the svg ?

**Pull request merged**
