### PR TITLE
[Gssoc'21] Enhancement in social media icons

### LINKED ISSUE #136: Enhancement in social media icons
### **Feature request**:
Cool and attractive social media icons in footer.

### **Is your feature request related to a problem? Please describe. (optional)**:
Social media icons are very dull and static

### **Describe the solution you'd like**:
I would like to make social media icons more attractive and want to add animation to it

### **Describe how this feature will be useful to our readers**:
A clear and concise description of how this feature will be useful for our  other readers.

### **Additional context:**

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

### PR DESCRIPTION
**Pull request by arpit456jain**
# Description:
I had replaced previous social media icons with these
icons

Fixes #136 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

 
# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

# Screenshots / Video:

https://user-images.githubusercontent.com/55352601/114820789-30621680-9ddd-11eb-95c7-b0d5a781dd2e.mp4

### CODE REVIEW

**Comment by arpit456jain** [comment]
proact 1

I had replaced the YouTube with GitHub

**Comment by arpit456jain** [comment]
@SaiSudhaV kindly add gssoc labels

**Comment by arpit456jain** [comment]
@sruti2024 @SaiSudhaV @PROTechThor any one please review my PR

**Comment by arpit456jain** [comment]
@PROTechThor @SaiSudhaV @sruti2024 please review my PR some conflicts are occurring i had solved them  actually may be someone added the what's app icon so I have to write the new css for it but i had done this .
Its looking like this
pro new

**Comment by arpit456jain** [comment]
social media

**Comment by arpit456jain** [comment]
@sruti2024 @SaiSudhaV

**Comment by sruti2024** [comment]
please could u reduce the icon size 
@PROTechThor do check on this

**Comment by arpit456jain** [comment]
> please could u reduce the icon size
> @PROTechThor do check on this

@sruti2024 This was the optimal size but i had decreased them a little bit 
pro new

**Comment by arpit456jain** [comment]
@sruti2024 @SaiSudhaV @PROTechThor

**Review by PROTechThor — APPROVED** [review]
Looks great! Where did you get the icons from, by the way? Just to make sure there are no copyright issues.

**Comment by arpit456jain** [comment]
> Looks great! Where did you get the icons from, by the way? Just to make sure there are no copyright issues.

From code pen and after that i had made the lot's of changes don't worry there will be no copyright issues

**Comment by arpit456jain** [comment]
@sruti2024 @SaiSudhaV pr is approved. Please merge it

**Pull request merged**
