### PR TITLE
Enhance Index CSS 

### LINKED ISSUE #70: Enhance the CSS of the Index Page
### **Feature request**:
Enhance the UI/UX  of the index page , can have some graphs showing the no of projects created , latest project created etc.

### **Is your feature request related to a problem? Please describe. (optional)**:
The problem is that the interface is very simple and needs enhancement

### **Describe the solution you'd like**:
Animations , pictures any enhancement that will improve the view keeping the same color scheme will do great !

### **Describe how this feature will be useful to our readers**:
An interesting index page will attract more people!
<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone. 
* First create the design get it verified by the mentors and then move on with the coding also while making the pr attach a ss or video along with it !

### PR DESCRIPTION
**Pull request by SalmaFarghaly**
# Description:
Enhancing the CSS of index page and adding some graphs representing the activity of user
Independencies :
bokeh==2.3.0
django-chartjs==2.2.1

Fixes #70 

Please Note that I have commented the footer part while recording the video because it appears over the new graph content in the Index page 
# Screenshots / Video:

https://user-images.githubusercontent.com/59613960/113619302-1a27be00-9659-11eb-8ba1-fde1fcbed172.mp4

It looks like this with the footer component
withfooter

### CODE REVIEW

**Comment by sruti2024** [comment]
wonderful execution!! great work , but is the footer overlapping or something ?

**Comment by SalmaFarghaly** [comment]
@sruti2024 yes it is overlapping over a part of screen as shown in attached screenshot
withfooter

**Comment by SalmaFarghaly** [comment]
@sruti2024 yes it is overlapping over a part of screen as shown in attached screenshot
withfooter

**Comment by SaiSudhaV** [comment]
@SalmaFarghaly Please try to resolve the merge conflicts.

**Comment by SalmaFarghaly** [comment]
@SaiSudhaV the "Resolve conflicts" button is unclickable , I was working on a branch called "IndexCSS" in the forked repo
image

**Comment by SalmaFarghaly** [comment]
@SaiSudhaV 
Done I have solved the conflicts

**Pull request merged**
