### PR TITLE
added functionality of subtasks

### LINKED ISSUE #114: [GSSOC '21] Adding Sub Task Functionality to Manage Projects
### **Feature request**:
When we click on the manage project button for any specific project we get a page with some information on the right along with a "Add Subtask" button which just opens up a dialogue box but this box provides no functionality and doesn't add any subtask.

### **Describe the solution you'd like**:
I would like to create model for storing the sub tasks related to each project and also display them accurately under specific projects when the user goes to the manage section of a project.

### **Describe how this feature will be useful to our readers**:
This will help teams in managing the project in a more agile and systematic manner.

### **Additional context:**
I'm GSSOC '21 participant and would like to work on this issue so kindly assign me the same.

### PR DESCRIPTION
**Pull request by niksm7**
# Description:

Previously there was only project information shown when the user clicked on manage but now the user can actually add subtasks, mark them as complete and delete whichever task they want. Everything is made dynamic and will effect the database directly. 
Also to mention that all the subtasks are specific to the projects and will show only under that particular project.

Fixes #114 

## Type of change:

- [x] New feature (non-breaking change which adds functionality)

 
# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] My changes generate no new warnings.
- [x] New and existing unit tests pass locally with my changes.
- [x] Any dependent changes have been merged and published in downstream modules.

# Screenshots / Video:

https://user-images.githubusercontent.com/55614782/113894556-c0083380-97e5-11eb-924c-79327f181504.mov

### CODE REVIEW

**Comment by niksm7** [comment]
@SaiSudhaV @sruti2024  Please review this PR.

**Comment by sruti2024** [comment]
seems alright just change the table style , add a table header and also instead of the square box, just have a button which is incomplete initially and on click turns into complete

**Comment by niksm7** [comment]
Can you please explain to me what do you mean by table header by taking a screenshot of that part in the video? Also, I tried the button and it doesn't look very good with the UI, do you still want me to go ahead with it? 
@sruti2024

**Review by Saipriyavadisina — APPROVED** [review]

**Review by SaiSudhaV — APPROVED** [review]

**Comment by sruti2024** [comment]
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Project name</th>
      <th scope="col">Description</th>
      <th scope="col">Status</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td>Project 1</td>
      <td>Demonstration</td>
      <td>Active</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>project 2</td>
      <td>Demonstration 2</td>
      <td>completed</td>
    </tr>
   
  </tbody>
</table>

want the table to look some what similar to this , header means the heading like project name , description  and status,
if the button for status is not looking good change it to a badge

**Comment by niksm7** [comment]
https://user-images.githubusercontent.com/55614782/114503594-34f6c580-9c4b-11eb-8ac5-1854a3c21502.mov

Have done the required changes. Please check this out @sruti2024 @SaiSudhaV

**Comment by sruti2024** [comment]
Really wonderful work , please resolve the conflict and it will get merged !!

**Comment by niksm7** [comment]
Conflicts have been resolved @sruti2024

**Pull request merged**
