### PR TITLE
fixed a bug in 404 page

### LINKED ISSUE #202: bug in 404 error page
bug in 404 error page
its looking like this 
dhid

### PR DESCRIPTION
**Pull request by arpit456jain**
# Description:

fixed a bug in 404 page
previously
dhid

now
aaaaa

Fixes #202 

## Type of change:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

 
# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

# Screenshots / Video:

### CODE REVIEW

**Comment by arpit456jain** [comment]
@SaiSudhaV @PROTechThor @sruti2024 kindly review this PR

**Comment by SaiSudhaV** [comment]
@arpit456jain Is External css creating bug?

**Comment by arpit456jain** [comment]
> @arpit456jain Is External CSS creating a bug?

Yes... when debug is false django doesn't render css locally

**Comment by arpit456jain** [comment]
So it's good practice to keep css for 404 page in it .
No need to make a separate css file

**Comment by arpit456jain** [comment]
@SaiSudhaV some times its good to be internal css rather than external 🙂.

**Review by SaiSudhaV — APPROVED** [review]

**Comment by arpit456jain** [comment]
@sruti2024 kindly merge this PR and add labels to it

**Comment by Aryamanz29** [comment]
> @arpit456jain Is External CSS creating a bug?

Nope, because when you SET `DEBUG=False,` Django doesn't load static files for this we have to use the `--insecure` flag while running server. ie  `python manage.py runserver --insecure` 

**See this Stackoverflow Question**: https://stackoverflow.com/questions/31097333/why-is-serving-static-files-insecure

@arpit456jain  I think this is not a bug if you follow the above instructions, you see  **404.html** load with **external CSS**

Note: In the future, if project admin wants to deploy this app, they could use **collectstatic**  which ensures all static files load properly.

**See I've tested locally :** :point_down: 

Screenshot from 2021-05-29 16-34-49

**Comment by arpit456jain** [comment]
@Aryamanz29  First thing  are you mentor ? ?

Second thing . I dont't know about --insecure if its true then may be you are right..

Third what's the big deal if we put css internally ?

Fourth main purpose of creating external css is to reduce code , the css which is being used in more than one page is preferred
to put externally  .
No need of making all css external it slow down the loading capacity of page .

@SaiSudhaV @sruti2024 if you think this PR is good yo be merged , please merged it . or you can close it no problem to me .
thank You

**Comment by Aryamanz29** [comment]
> @Aryamanz29 First thing are you mentor ? ?
> 
> Second thing . I dont't know about --insecure if its true then may be you are right..
> 
> Third what's the big deal if we put css internally ?
> 
> Fourth main purpose of creating external css is to reduce code , the css which is being used in more than one page is preferred
> to put externally .
> No need of making all css external it slow down the loading capacity of page .
> 
> @SaiSudhaV @sruti2024 if you think this PR is good yo be merged , please merged it . or you can close it no problem to me .
> thank You

-  **Ans 1**. I'm not a mentor, and in open source, anyone can discuss and put their opinion 

-  **Ans 2.**  I have already commented in setting.py about `--insecure `and `404 custom page`. 

-  **Ans3.**  Code is not maintainable if we have internal css, and it's indigestible for new contributors. Everyone should follow similar code writing practices and maintain modularity.
-  **Ans4.** Yes, but also external static files are cached,  which makes the page smooth and quicker.

**Comment by arpit456jain** [comment]
@SaiSudhaV  @sruti2024  can you add labels please

**Comment by arpit456jain** [comment]
@SaiSudhaV @sruti2024 @PROTechThor labels ??

**Pull request merged**
