### PR TITLE
Added module page

### PR DESCRIPTION
**Pull request by kalpanapurohit**
Following changes has been made:- 
1. On click of manage button it open a module page for that project containing all the details of project.
2. Added a button in module page to add subtask and on clicking that button it is showing a model popup to take subtask details.
3. Created a new table named "modules_add" to store subtask data and is linked to project_add table using foreign key.

Fixes # (issue no. 5)

### CODE REVIEW

**Comment by SaiSudhaV** [comment]
Hi @kalpanapurohit
Can you please add the demo video and try to resolve the merge conflicts
Thank you

**Comment by kalpanapurohit** [comment]
[Presentation2.pptx](https://github.com/sruti2024/PRO_Act/files/6215375/Presentation2.pptx)

**Comment by sruti2024** [comment]
@kalpanapurohit the file given by u contains only one picture and that does not show the whole functioning , so please attach a video also please make changes in the latest file this would resolve the conflicts , i.e unfork  and the fork the repo once again , and clone the repo once again

**Comment by kalpanapurohit** [comment]
hey @sruti2024 that's a complete video and not just one picture. please click the play button at the left corner in the slide.

**Comment by SaiSudhaV** [comment]
@kalpanapurohit The ppt is just having a picture the video is not working check it again and try resolving merge conflicts, as mentioned by @sruti2024, unfork and fork the repo again

**Pull request closed without merging**
