### PR TITLE
Module Page

### PR DESCRIPTION
**Pull request by kalpanapurohit**
Fixes #issue 5

### CODE REVIEW

**Comment by SaiSudhaV** [comment]
@kalpanapurohit Please attach the working demo video

**Comment by kalpanapurohit** [comment]
https://user-images.githubusercontent.com/35923962/113471393-9499e780-9479-11eb-9a09-cc788d842a25.mp4

**Comment by SaiSudhaV** [comment]
Tag the issue @kalpanapurohit

**Comment by kalpanapurohit** [comment]
#5

**Pull request merged**
