### PR TITLE
 Move : Internal CSS to External

### LINKED ISSUE #168: Move : Internal & Inline CSS to external CSS
### Description :
- I found templates having inline and internal CSS which is indigestible to new contributors.

Screenshot (91)

Screenshot (92)

### Expected : 

- Remove all inline and internal CSS to external CSS and place them into the ` ./static/` directory also do necessary changes to the project codebase to work the same as before.

### PR DESCRIPTION
**Pull request by Aryamanz29**
# Description:

-  Moved  internal CSS to external CSS.
-  Format HTML files. 
-  Move all CSS files to `static/css/` .
-  Delete redundant HTML files ( ie . `base_BACKUP_1831.html base_BASE_1831.html base_LOCAL_1831.html base_REMOTE_1831.html`) from `templates/`
-  Locally perform the test for this PR ✔, attached `gif` below👇

Fixes #168

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

 
# Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] Any dependent changes have been merged and published in downstream modules.

# Screenshots / Video 📸:
css_wroking-low

### CODE REVIEW

**Comment by Aryamanz29** [comment]
@sruti2024 @SaiSudhaV @PROTechThor  Need Review for this PR 📝

**Comment by SaiSudhaV** [comment]
@Aryamanz29 There are some files that still have inline styling. Can't they be moved to an external file?

**Comment by Aryamanz29** [comment]
@SaiSudhaV  Thanks for pointing it out. 
We can't move those inline styling because that creates a mess or may they overwrite the existing CSS, also if any chance I could move them to the external file they need proper ` Classes & ID` names for specific HTML element and that's very hard for me to do because those designs aren't implemented by me.

**Comment by SaiSudhaV** [comment]
@Aryamanz29 Thanks for clarifying

**Comment by Aryamanz29** [comment]
> @Aryamanz29 Thanks for clarifying

@SaiSudhaV  Please add `gssoc` and `level` label to this PR

**Comment by Aryamanz29** [comment]
> > @Aryamanz29 Thanks for clarifying
> 
> @SaiSudhaV @sruti2024 Please add `gssoc` and `level` label to this PR

**Pull request merged**
